// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_profile from "./routes/[id]/profile.tsx";
import * as $_id_todos from "./routes/[id]/todos.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth from "./routes/api/auth.ts";
import * as $index from "./routes/index.tsx";
import * as $LogIn from "./islands/LogIn.tsx";
import * as $ToDoList from "./islands/ToDoList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id]/profile.tsx": $_id_profile,
    "./routes/[id]/todos.tsx": $_id_todos,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth.ts": $api_auth,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/LogIn.tsx": $LogIn,
    "./islands/ToDoList.tsx": $ToDoList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
